version: "3"

services:
  db:
    image: mdillon/postgis:9.5
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
      POSTGRES_DB: authservice

volumes:
  db_data:
    driver: local
